name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, sqlite, bcmath, curl, opcache, zip

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Set APP_KEY for testing environment
      run: |
        echo "APP_KEY=$(php -r 'echo base64_encode(random_bytes(32));')" >> .env.testing

    - name: Create SQLite database file if it doesn't exist
      run: |
        mkdir -p database  # Ensure the database folder exists
        touch database/database.sqlite  # Create the SQLite file if it doesn't exist

    - name: Copy .env.testing to .env
      run: |
        cp .env.testing .env

    - name: Run Tests
      env:
        APP_KEY: ${{ secrets.APP_KEY }}  # Explicitly set the APP_KEY for the test environment
        APP_ENV: testing  # Set to testing environment explicitly
      run: |
        php artisan migrate --env=testing  # Run migrations
        php artisan test --env=testing  # Run tests

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, sqlite, bcmath, curl, opcache, zip

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          cd /path/to/your/project
          git pull origin master
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan queue:restart
        EOF
