name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, sqlite, bcmath, curl, opcache, zip

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Set APP_KEY for testing environment
      run: |
        echo "APP_KEY=$(php -r 'echo base64_encode(random_bytes(32));')" >> .env.testing
        cat .env.testing  # Debugging: output the contents of .env.testing

    - name: Set absolute database path in .env.testing
      run: |
        echo "DB_CONNECTION=sqlite" >> .env.testing
        echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env.testing
        cat .env.testing  # Verify the database path in .env.testing

    - name: Copy .env.testing to .env
      run: |
        cp .env.testing .env
        cat .env  # Debugging: output the contents of .env to ensure APP_KEY and DB_DATABASE are set correctly

    - name: Clear config cache
      run: |
        php artisan config:clear
        php artisan cache:clear

    - name: Check if SQLite database exists and create if necessary
      run: |
        echo "Checking if SQLite database file exists..."
        if [ ! -f database/database.sqlite ]; then
          echo "SQLite database not found, creating it..."
          touch database/database.sqlite
          echo "Database file created at $(pwd)/database/database.sqlite"
        else
          echo "SQLite database already exists"
        fi

    - name: Run Migrations
      run: |
        echo "Running migrations..."
        php artisan migrate --env=testing

    - name: Run Tests
      if: ${{ github.event.inputs.skip_tests != 'true' }}
      env:
        APP_KEY: ${{ secrets.APP_KEY }}  # Explicitly set APP_KEY from secrets, if available
        APP_ENV: testing  # Set to testing environment
      run: |
        php artisan test --env=testing

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          cd /path/to/your/project
          git pull origin master
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan queue:restart
        EOF
