root@DESKTOP-O81JFQ2:/home/sumit/cicd_website# cat .github/workflows/ci.yml
name:CI Workflow

on:
  # Trigger when code is pushed to the master branch
  push:
    branches:
      - master
  # Enable manual trigger from the Actions tab
  workflow_dispatch:





jobs:
  build:
    runs-on: ubuntu-latest
    - name: Set up SSH key for GitHub
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: sumit
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, opcache, zip

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Configure Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=isitca-all.c4hva0l5qlqf.ap-south-1.rds.amazonaws.com/' .env
        sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel_db/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=sumit/' .env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}/" .env

    - name: Debug Environment
      run: cat .env

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e 'show databases;'; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Clear config cache
      run: |
        php artisan config:clear

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: isitca-all.c4hva0l5qlqf.ap-south-1.rds.amazonaws.com
        DB_PORT: 3306
        DB_DATABASE: laravel_db
        DB_USERNAME: sumit
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        APP_ENV: testing
      run: |
        php artisan migrate --env=testing --force
        php artisan test
