jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: my_laravel_db
          MYSQL_USER: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, curl, opcache, zip

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Configure Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        # Update the .env file for MySQL
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env  # Use mysql service
        sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=my_laravel_db/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}/' .env

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'show databases;'; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Clear config cache
      run: |
        php artisan config:clear

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: mysql  # Use mysql service
        DB_PORT: 3306
        DB_DATABASE: my_laravel_db
        DB_USERNAME: root
        DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        APP_ENV: testing
      run: |
        php artisan migrate --force  # Run migrations
        php artisan test  # Run tests
