name: CI/CD Pipeline to WSL

on:
  push:
    branches:
      - master  # Trigger this action when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the GitHub-hosted Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Connection
        run: ssh -v -o StrictHostKeyChecking=no sumit@172.20.240.1 echo "Connection successful"

      - name: Deploy to WSL
        run: |
          ssh -o StrictHostKeyChecking=no sumit@127.0.0.1 << 'EOF'
            cd /home/sumit/cicd_website
            git pull origin master
            # Add additional deployment commands here, e.g., clearing cache, restarting services
          EOF
